---
- name: Update Servers  
  hosts: all
  
  tasks:
  - name: Reboot machine using a custom reboot command
    reboot:
      reboot_command: launchctl reboot userspace
      boot_time_command: uptime | cut -d ' ' -f 5
